WITH DONACIONES AS (
	SELECT C.ANYO_MES,
	SUM(D.IMPORTE_EUR) AS IMPORTE_DINERO
	FROM DIM_CALENDARIO C INNER JOIN FACT_DONACIONES_ECO D
	ON C.FECHA=D.FECHA
	GROUP BY C.anyo_mes
),
ENTRADAS AS (
	SELECT C.ANYO_MES,
	SUM(E.KG_RECIBIDOS) AS KG_RECIBIDOS
	FROM DIM_CALENDARIO C INNER JOIN FACT_ENTRADAS E
	ON C.FECHA=E.fecha
	GROUP BY C.anyo_mes
)
SELECT D.ANYO_MES,
(D.IMPORTE_DINERO) AS 'IMPORTE EUROS',
(E.KG_RECIBIDOS) AS 'KG RECIBIDOS',
ROUND(((D.IMPORTE_DINERO/E.KG_RECIBIDOS)),2) AS 'EUROS/KG'
FROM DONACIONES D INNER JOIN ENTRADAS E
ON D.ANYO_MES=E.anyo_mes
ORDER BY (D.IMPORTE_DINERO / E.KG_RECIBIDOS) DESC;
