SELECT COUNT (E.NOMBRE) AS NOMBRE_ENTIDADES,
	CASE 
		WHEN(E.PERSONAS_ATENDIDAS)>=500 THEN 'GRANDE'
		WHEN(E.PERSONAS_ATENDIDAS)>=200 AND (E.PERSONAS_ATENDIDAS) <500  THEN 'MEDIANA'
		WHEN(E.PERSONAS_ATENDIDAS)<200 THEN 'PEQUEÑA'
	END AS TRAMO_ENTIDADES,
ROUND(AVG(E.PERSONAS_ATENDIDAS),1) AS MEDIA_PERSONAS_ATENDIDAS
FROM DIM_ENTIDAD E
GROUP BY TRAMO_ENTIDADES
	
